# 多Profile文件
server:
    port: 8081
spring:
    profiles:
        active: pro
---

server:
    port: 8083
spring:
    profiles: dev
---

server:
    port: 8084
spring:
    profiles: prod  #指定属于哪个环境

debug=true