spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://172.16.0.192:3306/dbshiro?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    initial-size: 1
    min-idle: 1
    max-active: 20
    test-on-borrow: true
    # MySQL 8.x: com.mysql.cj.jdbc.Driver
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  type-aliases-package: cn.zysheep.springboot.entity
  mapper-locations: classpath:mapper/*.xml
server:
  port: 9090